import type { Metadata } from "next";

export const SEO_CONFIG = {
  brandName: "BookBy247",
  alternateBrandNames: ["bookby247", "Book By 247", "Book by 24/7"],
  baseUrl: "https://bookby247.com",
  defaultTitle: "BookBy247 | India's First & Largest Spa, Salon & Beauty Discovery, Booking Platform & CRM",
  defaultDescription:
    "BookBy247 is India's first and largest spa, salon & beauty discovery and booking platform & CRM. Discover top beauty experts near you and book appointments online instantly.",
  defaultKeywords: [
    "BookBy247",
    "bookby247",
    "Book By 247",
    "spa booking",
    "salon booking",
    "wellness booking",
    "spa near me",
    "salon near me",
    "beauty parlour near me",
    "beauty salon near me",
    "massage near me",
    "massage spa near me",
    "body massage center near me",
    "hair salon near me",
    "ladies salon near me",
    "men salon near me",
    "unisex salon near me",
    "spa booking online",
    "salon booking online",
    "online spa appointment",
    "online salon appointment",
    "beauty services near me",
    "best spa near me",
    "best salon near me",
    "body massage near me",
    "full body massage near me",
    "deep tissue massage near me",
    "aromatherapy massage near me",
    "thai massage near me",
    "couple spa near me",
    "facial near me",
    "cleanup facial near me",
    "skin care salon near me",
    "haircut near me",
    "hair spa near me",
    "hair colouring near me",
    "keratin treatment near me",
    "beard grooming near me",
    "manicure pedicure near me",
    "nail art near me",
    "bridal makeup near me",
    "makeup artist near me",
    "waxing near me",
    "threading near me",
    "body polishing near me",
    "luxury spa near me",
    "affordable salon near me",
    "spa offers near me",
    "salon deals near me",
    "spa in Mumbai",
    "salon in Mumbai",
    "spa in Navi Mumbai",
    "salon in Navi Mumbai",
    "salon in Delhi",
    "spa in Delhi",
    "beauty parlour in Bangalore",
    "salon in Bangalore",
    "spa in Pune",
    "salon in Hyderabad",
    "spa in Hyderabad",
    "beauty services in India",
    "massage in Navi Mumbai",
    "book spa appointment online",
    "book salon appointment online",
    "top rated salons with reviews",
    "top rated spas with reviews",
    "spa management software",
    "salon management software",
    "beauty business management software",
    "spa appointment management",
    "salon CRM software",
    "multi branch salon management",
    "spa inventory management",
    "salon campaign management",
    "beauty salon billing software",
    "spa in Hosa Road",
    "massage spa Hosa Road",
    "local spa treatments near me",
    "couple spa in Hosa Road",
    "nearest day spa",
    "nearby spa massage",
    "body spa near me",
    "massage service in Hosa Road",
    "best massage spa Hosa Road",
    "couples spa",
    "spa days near me",
    "spa experience",
    "spa near Hosa Road",
    "massage spa center near me",
    "body spa massage near me",
    "massage therapy massage near me",
    "sports massage near me",
    "best spa Hosa Road",
    "aroma thai spa Hosa Road",
    "body massage spa in Hosa Road",
    "luxury spa",
    "relaxation spa",
    "massage center in Hosa Road",
    "luxury massage spa",
    "couple massage in Hosa Road",
    "body spa",
    "near by spa center",
    "thai massage massage near me",
    "near by me massage center",
    "spa wellness center near me",
    "best body massage near me",
    "find massage places near me",
    "nearest spa centre",
    "body massage center",
    "best body spa near me",
    "near by thai massage",
    "best massage spa near me",
    "luxury spa weekend near me",
    "massage near me now",
    "massage spa and sauna near me",
    "best spa in location",
    "best massage in location",
    "best body spa in location",
    "best body massage in location",
    "spa & massage services",
    "luxury spa in location",
  ],
  ogImage: {
    url: "https://res.cloudinary.com/dwsv275kv/image/upload/v1774691836/555666_m75jkf.png",
    width: 1200,
    height: 630,
    alt: "BookBy247 online spa, salon and wellness booking platform",
  },
  contactEmail: "support@bookby247.com",
  contactPhone: "+91-9082029142",
  locale: "en_IN",
  twitterHandle: "@bookby247",
  themeColor: "#111827",
} as const;

export const publicRoutes = [
  { path: "/", priority: 1, changeFrequency: "daily" as const },
  { path: "/explore", priority: 0.9, changeFrequency: "daily" as const },
  { path: "/blog", priority: 0.9, changeFrequency: "daily" as const },
  { path: "/blog/latest", priority: 0.8, changeFrequency: "daily" as const },
  { path: "/blog/popular", priority: 0.8, changeFrequency: "daily" as const },
  { path: "/blog/trending", priority: 0.8, changeFrequency: "daily" as const },
  { path: "/free-listing", priority: 0.8, changeFrequency: "monthly" as const },
  { path: "/careers", priority: 0.5, changeFrequency: "monthly" as const },
  { path: "/editorial-standards", priority: 0.5, changeFrequency: "monthly" as const },
  { path: "/privacy-policy", priority: 0.3, changeFrequency: "monthly" as const },
  { path: "/terms-of-service", priority: 0.3, changeFrequency: "monthly" as const },
  { path: "/cookies-settings", priority: 0.2, changeFrequency: "yearly" as const },
];

import { createCanonicalUrl } from "./seo-url";

export const toAbsoluteUrl = (path = "/") => createCanonicalUrl(path);

export const defaultOpenGraph: Metadata["openGraph"] = {
  title: SEO_CONFIG.defaultTitle,
  description: SEO_CONFIG.defaultDescription,
  url: SEO_CONFIG.baseUrl,
  siteName: SEO_CONFIG.brandName,
  locale: SEO_CONFIG.locale,
  type: "website",
  images: [SEO_CONFIG.ogImage],
};

export const defaultTwitter: Metadata["twitter"] = {
  card: "summary_large_image",
  title: SEO_CONFIG.defaultTitle,
  description: SEO_CONFIG.defaultDescription,
  images: [SEO_CONFIG.ogImage.url],
  creator: SEO_CONFIG.twitterHandle,
};

export const indexFollowRobots: Metadata["robots"] = {
  index: true,
  follow: true,
  googleBot: {
    index: true,
    follow: true,
    "max-video-preview": -1,
    "max-image-preview": "large",
    "max-snippet": -1,
  },
};

export const noIndexRobots: Metadata["robots"] = {
  index: false,
  follow: false,
  googleBot: {
    index: false,
    follow: false,
  },
};
