import type { Metadata } from "next"
import Link from "next/link"
import { blogApi } from "@/api/public/blog"
import { Sparkles, Cpu, Zap, Search, ArrowRight, Bot, Compass, ShieldCheck } from "lucide-react"

export const metadata: Metadata = {
    title: "AI Articles & Insights | Luomo AI Blog Hub",
    description:
        "Explore cutting-edge, AI-crafted & human-curated articles on technology, local business growth, and digital trends generated by Luomo AI.",
    openGraph: {
        title: "AI Articles & Insights | Luomo AI Blog Hub",
        description:
            "Explore cutting-edge, AI-crafted & human-curated articles generated by Luomo AI.",
        type: "website",
    },
}

export const revalidate = 300

export default async function AiBlogsPage({
    searchParams,
}: {
    searchParams: Promise<{ q?: string; category?: string }>
}) {
    const resolvedParams = await searchParams
    const query = resolvedParams.q || ""
    const selectedCategory = resolvedParams.category || ""

    let blogs: any[] = []
    let categories: any[] = []

    try {
        const [blogsRes, catRes] = await Promise.all([
            blogApi.listBlogs({ limit: 12, search: query, category: selectedCategory }),
            blogApi.getCategories(),
        ])
        blogs = blogsRes.data || []
        categories = catRes.data || []
    } catch {
        /* fallback empty array */
    }

    return (
        <div className="min-h-screen bg-slate-950 text-slate-100 selection:bg-indigo-500 selection:text-white">
            {/* Ambient Background Blur Elements */}
            <div className="pointer-events-none fixed top-0 left-1/4 h-[500px] w-[500px] -translate-y-1/2 rounded-full bg-indigo-600/20 blur-[140px]" />
            <div className="pointer-events-none fixed top-1/3 right-10 h-[400px] w-[400px] rounded-full bg-purple-600/15 blur-[120px]" />

            {/* Hero Section */}
            <header className="relative border-b border-slate-800/80 bg-slate-950/80 backdrop-blur-xl pt-16 pb-20 px-4 sm:px-8">
                <div className="mx-auto max-w-6xl text-center">
                    <div className="inline-flex items-center gap-2 rounded-full border border-indigo-500/30 bg-indigo-500/10 px-4 py-1.5 text-xs font-semibold text-indigo-300 shadow-sm backdrop-blur-md mb-6">
                        <Sparkles className="h-4 w-4 animate-pulse text-amber-400" />
                        <span>Powered by Luomo AI Engine</span>
                    </div>

                    <h1 className="text-4xl sm:text-6xl font-extrabold tracking-tight text-white max-w-3xl mx-auto leading-tight">
                        AI-Crafted Insights &{" "}
                        <span className="bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400 bg-clip-text text-transparent">
                            Smart Knowledge Hub
                        </span>
                    </h1>

                    <p className="mt-5 text-base sm:text-lg text-slate-400 max-w-2xl mx-auto leading-relaxed">
                        Discover deeply researched, SEO-rich articles automatically generated by Luomo AI and curated by expert editors.
                    </p>

                    {/* Features Badges */}
                    <div className="mt-8 flex flex-wrap items-center justify-center gap-4 text-xs font-medium text-slate-400">
                        <div className="flex items-center gap-1.5 rounded-xl border border-slate-800 bg-slate-900/60 px-3.5 py-2">
                            <Zap className="h-4 w-4 text-amber-400" />
                            <span>Instant SEO Optimization</span>
                        </div>
                        <div className="flex items-center gap-1.5 rounded-xl border border-slate-800 bg-slate-900/60 px-3.5 py-2">
                            <Cpu className="h-4 w-4 text-indigo-400" />
                            <span>Structured FAQ & Schemas</span>
                        </div>
                        <div className="flex items-center gap-1.5 rounded-xl border border-slate-800 bg-slate-900/60 px-3.5 py-2">
                            <ShieldCheck className="h-4 w-4 text-emerald-400" />
                            <span>Human Verified Content</span>
                        </div>
                    </div>
                </div>
            </header>

            {/* Main Content Area */}
            <main className="mx-auto max-w-7xl px-4 py-12 sm:px-8">
                {/* Category Filters */}
                {categories.length > 0 && (
                    <div className="mb-10 flex flex-wrap items-center justify-center gap-2">
                        <Link
                            href="/blog/ai"
                            className={`rounded-xl px-4 py-2 text-xs font-semibold transition-all ${
                                !selectedCategory
                                    ? "bg-indigo-600 text-white shadow-lg shadow-indigo-600/30"
                                    : "bg-slate-900/80 text-slate-400 hover:bg-slate-800 hover:text-white border border-slate-800"
                            }`}
                        >
                            All AI Articles
                        </Link>
                        {categories.map((cat: any) => {
                            const isSelected = selectedCategory === cat.slug
                            return (
                                <Link
                                    key={cat._id || cat.slug}
                                    href={`/blog/ai?category=${cat.slug}`}
                                    className={`rounded-xl px-4 py-2 text-xs font-semibold transition-all ${
                                        isSelected
                                            ? "bg-indigo-600 text-white shadow-lg shadow-indigo-600/30"
                                            : "bg-slate-900/80 text-slate-400 hover:bg-slate-800 hover:text-white border border-slate-800"
                                    }`}
                                >
                                    {cat.name}
                                </Link>
                            )
                        })}
                    </div>
                )}

                {/* Blog Grid */}
                {blogs.length === 0 ? (
                    <div className="rounded-3xl border border-slate-800 bg-slate-900/40 p-12 text-center max-w-xl mx-auto my-12">
                        <Bot className="h-12 w-12 text-indigo-400 mx-auto mb-4" />
                        <h3 className="text-lg font-bold text-white">No AI Articles Found</h3>
                        <p className="text-xs text-slate-400 mt-2">
                            Check back soon or explore our general blog articles.
                        </p>
                        <Link
                            href="/blog"
                            className="mt-6 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-2.5 text-xs font-bold text-white hover:bg-indigo-500 transition-colors"
                        >
                            <Compass className="h-4 w-4" />
                            <span>Browse All Articles</span>
                        </Link>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {blogs.map((blog: any) => (
                            <article
                                key={blog.id || blog._id || blog.slug}
                                className="group relative flex flex-col justify-between overflow-hidden rounded-3xl border border-slate-800/80 bg-slate-900/40 p-6 backdrop-blur-xl transition-all duration-300 hover:-translate-y-1 hover:border-indigo-500/40 hover:shadow-xl hover:shadow-indigo-500/10"
                            >
                                <div>
                                    {/* Cover Image */}
                                    {blog.featuredImage?.url ? (
                                        <div className="relative aspect-[16/9] w-full overflow-hidden rounded-2xl mb-5 bg-slate-800">
                                            <img
                                                src={blog.featuredImage.url}
                                                alt={blog.featuredImage.alt || blog.title}
                                                className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
                                            />
                                            <div className="absolute top-3 right-3 rounded-full bg-slate-950/80 backdrop-blur px-2.5 py-1 text-[10px] font-bold text-indigo-300 border border-indigo-500/30 flex items-center gap-1">
                                                <Sparkles className="h-3 w-3 text-amber-400" />
                                                <span>Luomo AI</span>
                                            </div>
                                        </div>
                                    ) : (
                                        <div className="relative aspect-[16/9] w-full overflow-hidden rounded-2xl mb-5 bg-gradient-to-tr from-slate-900 via-indigo-950 to-purple-950 flex items-center justify-center border border-slate-800">
                                            <Bot className="h-10 w-10 text-indigo-400/50" />
                                            <div className="absolute top-3 right-3 rounded-full bg-slate-950/80 backdrop-blur px-2.5 py-1 text-[10px] font-bold text-indigo-300 border border-indigo-500/30 flex items-center gap-1">
                                                <Sparkles className="h-3 w-3 text-amber-400" />
                                                <span>Luomo AI</span>
                                            </div>
                                        </div>
                                    )}

                                    {/* Categories */}
                                    {blog.categories && blog.categories.length > 0 && (
                                        <div className="flex flex-wrap gap-1.5 mb-3">
                                            {blog.categories.map((cat: any) => (
                                                <span
                                                    key={cat.slug || cat._id}
                                                    className="rounded-md bg-indigo-500/10 px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-indigo-300 border border-indigo-500/20"
                                                >
                                                    {cat.name}
                                                </span>
                                            ))}
                                        </div>
                                    )}

                                    {/* Title */}
                                    <h2 className="text-xl font-bold tracking-tight text-white group-hover:text-indigo-300 transition-colors line-clamp-2">
                                        <Link href={`/blog/${blog.slug}`}>{blog.title}</Link>
                                    </h2>

                                    {/* Excerpt */}
                                    <p className="mt-2.5 text-xs text-slate-400 leading-relaxed line-clamp-3">
                                        {blog.excerpt || blog.ai?.summary || "Click to read the complete article breakdown..."}
                                    </p>
                                </div>

                                {/* Footer Info */}
                                <div className="mt-6 flex items-center justify-between border-t border-slate-800/60 pt-4 text-[11px] text-slate-500">
                                    <span>{blog.readingTimeMinutes || 2} min read</span>
                                    <Link
                                        href={`/blog/${blog.slug}`}
                                        className="flex items-center gap-1 font-semibold text-indigo-400 hover:text-indigo-300 transition-colors"
                                    >
                                        <span>Read Article</span>
                                        <ArrowRight className="h-3.5 w-3.5" />
                                    </Link>
                                </div>
                            </article>
                        ))}
                    </div>
                )}
            </main>
        </div>
    )
}
