name: 🚀 Deploy BookBy247 Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /var/www/book_by_247_public_frontend

            echo "📦 Pull latest code"
            git fetch --all
            git reset --hard origin/master

            echo "📥 Install dependencies"
            npm install

            echo "🏗 Build Next.js"
            npm run build

            echo "♻️ Restart app"
            pm2 reload bookby247-frontend

            echo "✅ Done"
